package pe.edu.unsch.entities;
// Generated 14/06/2019 04:32:06 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Modulo generated by hbm2java
 */
public class Modulo implements java.io.Serializable {

	private Integer idmodulo;
	private String nombre;
	private String icono;
	private Byte estado;
	private Set submodulos = new HashSet(0);

	public Modulo() {
	}

	public Modulo(String nombre, String icono, Byte estado, Set submodulos) {
		this.nombre = nombre;
		this.icono = icono;
		this.estado = estado;
		this.submodulos = submodulos;
	}

	public Integer getIdmodulo() {
		return this.idmodulo;
	}

	public void setIdmodulo(Integer idmodulo) {
		this.idmodulo = idmodulo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getIcono() {
		return this.icono;
	}

	public void setIcono(String icono) {
		this.icono = icono;
	}

	public Byte getEstado() {
		return this.estado;
	}

	public void setEstado(Byte estado) {
		this.estado = estado;
	}

	public Set getSubmodulos() {
		return this.submodulos;
	}

	public void setSubmodulos(Set submodulos) {
		this.submodulos = submodulos;
	}

}
