package pe.edu.unsch.entities;
// Generated 14/06/2019 04:32:06 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Opcion generated by hbm2java
 */
public class Opcion implements java.io.Serializable {

	private Integer idopcion;
	private Submodulo submodulo;
	private String nombre;
	private Byte estado;
	private Set perfilOpcions = new HashSet(0);

	public Opcion() {
	}

	public Opcion(Submodulo submodulo) {
		this.submodulo = submodulo;
	}

	public Opcion(Submodulo submodulo, String nombre, Byte estado, Set perfilOpcions) {
		this.submodulo = submodulo;
		this.nombre = nombre;
		this.estado = estado;
		this.perfilOpcions = perfilOpcions;
	}

	public Integer getIdopcion() {
		return this.idopcion;
	}

	public void setIdopcion(Integer idopcion) {
		this.idopcion = idopcion;
	}

	public Submodulo getSubmodulo() {
		return this.submodulo;
	}

	public void setSubmodulo(Submodulo submodulo) {
		this.submodulo = submodulo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Byte getEstado() {
		return this.estado;
	}

	public void setEstado(Byte estado) {
		this.estado = estado;
	}

	public Set getPerfilOpcions() {
		return this.perfilOpcions;
	}

	public void setPerfilOpcions(Set perfilOpcions) {
		this.perfilOpcions = perfilOpcions;
	}

}
