package pe.edu.unsch.entities;
// Generated 14/06/2019 04:32:06 PM by Hibernate Tools 5.3.0.Beta2

/**
 * PerfilOpcion generated by hbm2java
 */
public class PerfilOpcion implements java.io.Serializable {

	private Integer idperfilopcion;
	private Opcion opcion;
	private Perfil perfil;
	private Byte estado;

	public PerfilOpcion() {
	}

	public PerfilOpcion(Opcion opcion, Perfil perfil) {
		this.opcion = opcion;
		this.perfil = perfil;
	}

	public PerfilOpcion(Opcion opcion, Perfil perfil, Byte estado) {
		this.opcion = opcion;
		this.perfil = perfil;
		this.estado = estado;
	}

	public Integer getIdperfilopcion() {
		return this.idperfilopcion;
	}

	public void setIdperfilopcion(Integer idperfilopcion) {
		this.idperfilopcion = idperfilopcion;
	}

	public Opcion getOpcion() {
		return this.opcion;
	}

	public void setOpcion(Opcion opcion) {
		this.opcion = opcion;
	}

	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	public Byte getEstado() {
		return this.estado;
	}

	public void setEstado(Byte estado) {
		this.estado = estado;
	}

}
