package pe.edu.unsch.entities;
// Generated 14/06/2019 04:32:06 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Perfil generated by hbm2java
 */
public class Perfil implements java.io.Serializable {

	private Integer idperfil;
	private String nombre;
	private Set usuarioPerfils = new HashSet(0);
	private Set perfilOpcions = new HashSet(0);

	public Perfil() {
	}

	public Perfil(String nombre, Set usuarioPerfils, Set perfilOpcions) {
		this.nombre = nombre;
		this.usuarioPerfils = usuarioPerfils;
		this.perfilOpcions = perfilOpcions;
	}

	public Integer getIdperfil() {
		return this.idperfil;
	}

	public void setIdperfil(Integer idperfil) {
		this.idperfil = idperfil;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set getUsuarioPerfils() {
		return this.usuarioPerfils;
	}

	public void setUsuarioPerfils(Set usuarioPerfils) {
		this.usuarioPerfils = usuarioPerfils;
	}

	public Set getPerfilOpcions() {
		return this.perfilOpcions;
	}

	public void setPerfilOpcions(Set perfilOpcions) {
		this.perfilOpcions = perfilOpcions;
	}

}
