package pe.edu.unsch.entities;
// Generated 14/06/2019 04:32:06 PM by Hibernate Tools 5.3.0.Beta2

import java.util.HashSet;
import java.util.Set;

/**
 * Submodulo generated by hbm2java
 */
public class Submodulo implements java.io.Serializable {

	private Integer idsubmodulo;
	private Modulo modulo;
	private String nombre;
	private Byte estado;
	private Set opcions = new HashSet(0);

	public Submodulo() {
	}

	public Submodulo(Modulo modulo) {
		this.modulo = modulo;
	}

	public Submodulo(Modulo modulo, String nombre, Byte estado, Set opcions) {
		this.modulo = modulo;
		this.nombre = nombre;
		this.estado = estado;
		this.opcions = opcions;
	}

	public Integer getIdsubmodulo() {
		return this.idsubmodulo;
	}

	public void setIdsubmodulo(Integer idsubmodulo) {
		this.idsubmodulo = idsubmodulo;
	}

	public Modulo getModulo() {
		return this.modulo;
	}

	public void setModulo(Modulo modulo) {
		this.modulo = modulo;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Byte getEstado() {
		return this.estado;
	}

	public void setEstado(Byte estado) {
		this.estado = estado;
	}

	public Set getOpcions() {
		return this.opcions;
	}

	public void setOpcions(Set opcions) {
		this.opcions = opcions;
	}

}
