package pe.edu.unsch.entities;
// Generated 14/06/2019 04:32:06 PM by Hibernate Tools 5.3.0.Beta2

/**
 * UsuarioPerfil generated by hbm2java
 */
public class UsuarioPerfil implements java.io.Serializable {

	private Integer idusuarioperfil;
	private Perfil perfil;
	private Usuario usuario;
	private Byte estado;

	public UsuarioPerfil() {
	}

	public UsuarioPerfil(Perfil perfil, Usuario usuario) {
		this.perfil = perfil;
		this.usuario = usuario;
	}

	public UsuarioPerfil(Perfil perfil, Usuario usuario, Byte estado) {
		this.perfil = perfil;
		this.usuario = usuario;
		this.estado = estado;
	}

	public Integer getIdusuarioperfil() {
		return this.idusuarioperfil;
	}

	public void setIdusuarioperfil(Integer idusuarioperfil) {
		this.idusuarioperfil = idusuarioperfil;
	}

	public Perfil getPerfil() {
		return this.perfil;
	}

	public void setPerfil(Perfil perfil) {
		this.perfil = perfil;
	}

	public Usuario getUsuario() {
		return this.usuario;
	}

	public void setUsuario(Usuario usuario) {
		this.usuario = usuario;
	}

	public Byte getEstado() {
		return this.estado;
	}

	public void setEstado(Byte estado) {
		this.estado = estado;
	}

}
