package pe.edu.unsch.entities;
// Generated 14/06/2019 04:32:06 PM by Hibernate Tools 5.3.0.Beta2

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {

	private Integer idusuario;
	private String nombre;
	private String usuario;
	private String password;
	private String foto;
	private Byte estado;
	private Date ultimoLogin;
	private Set usuarioPerfils = new HashSet(0);

	public Usuario() {
	}

	public Usuario(String nombre, String usuario, String password, String foto, Byte estado, Date ultimoLogin,
			Set usuarioPerfils) {
		this.nombre = nombre;
		this.usuario = usuario;
		this.password = password;
		this.foto = foto;
		this.estado = estado;
		this.ultimoLogin = ultimoLogin;
		this.usuarioPerfils = usuarioPerfils;
	}

	public Integer getIdusuario() {
		return this.idusuario;
	}

	public void setIdusuario(Integer idusuario) {
		this.idusuario = idusuario;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public String getUsuario() {
		return this.usuario;
	}

	public void setUsuario(String usuario) {
		this.usuario = usuario;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getFoto() {
		return this.foto;
	}

	public void setFoto(String foto) {
		this.foto = foto;
	}

	public Byte getEstado() {
		return this.estado;
	}

	public void setEstado(Byte estado) {
		this.estado = estado;
	}

	public Date getUltimoLogin() {
		return this.ultimoLogin;
	}

	public void setUltimoLogin(Date ultimoLogin) {
		this.ultimoLogin = ultimoLogin;
	}

	public Set getUsuarioPerfils() {
		return this.usuarioPerfils;
	}

	public void setUsuarioPerfils(Set usuarioPerfils) {
		this.usuarioPerfils = usuarioPerfils;
	}

}
